#!/bin/sh

CURL=curl
PORT=443

CMDNAME=$(basename $0)

if [ -z $JWT_USER ]; then
  USER_ID=`id -u`
  DOWNLOAD_FOLDER=/tmp/jwt_user_u$USER_ID
  mkdir -p $DOWNLOAD_FOLDER
  DOWNLOAD_PATH="${DOWNLOAD_FOLDER}/token.jwt"
else
  DOWNLOAD_PATH=$JWT_USER
fi

while getopts s:l:p: OPT
do
  case $OPT in
    "s" ) HOST="$OPTARG" ;;
    "l" ) ACCOUNT="$OPTARG" ;;
    "p" ) PORT="$OPTARG" ;;
      * ) echo "Usage: $CMDNAME [-s HOST] [-l USER]" 1>&2
          exit 1 ;;
  esac
done

if [ -z "$HOST" -o -z "$ACCOUNT" ]; then
 echo "Usage: $CMDNAME [-s HOST] [-l USER]" 1>&2
 exit 1
fi

if [ -t 0 ]; then
  echo -n "Passphrase: "
  trap "stty echo" HUP INT QUIT TERM
  stty -echo
  read PASS
  stty echo

  echo
else
  read PASS
fi

URL=https://$HOST:$PORT/jwt-server/jwt

COMMAND="$CURL -sS -m 10 -X POST -d user=$ACCOUNT -d pass=$PASS $URL"

JWT=`$COMMAND`
curl_ret=$?
#curl's exit status is 0 at authentication error

expr "$JWT" : '.*Error.*' > /dev/null
jwt_ret=$?

if [ $curl_ret -ne 0 ] || [ -z "$JWT" ] || [ $jwt_ret -eq 0 ]; then
#error
  if [ $curl_ret -eq 0 ]; then
      echo "Authentication Error"
  fi
  exit 1
else
  echo "Output JWT to "$DOWNLOAD_PATH
  umask 077; echo $JWT > $DOWNLOAD_PATH
  exit 0
fi
