#!/bin/sh

CURL=curl

CMDNAME=$(basename $0)

if [ -n $JWT_SERVER_URL ]; then
  BASE_URL=$JWT_SERVER_URL
fi

if [ -n $LOGNAME ]; then
  ACCOUNT=$LOGNAME
fi

while getopts s:l:p: OPT
do
  case $OPT in
    "s" ) BASE_URL=$BASE_URL" ""$OPTARG" ;;
    "l" ) ACCOUNT="$OPTARG" ;;
      * ) echo "Usage: $CMDNAME [-s URL] [-l USER]" 1>&2
          exit 1 ;;
  esac
done

if [ -z "$BASE_URL" -o -z "$ACCOUNT" ]; then
 echo "Usage: $CMDNAME [-s URL] [-l USER]" 1>&2
 exit 1
fi

if [ -t 0 ]; then
  echo -n "Passphrase: "
  trap "stty echo" HUP INT QUIT TERM
  stty -echo
  read PASS
  stty echo

  echo
else
  read PASS
fi

set -- $BASE_URL
for i in `seq 1 $#`
do
    u=$(eval echo '$'${i})
    u=$(echo $u | sed 's:/*$::')
    URL=${u}'/chpass'

    echo "$u"

    COMMAND="$CURL -f -sS -m 10 -X POST -d user=$ACCOUNT -d pass=$PASS $URL"

    PASSPHRASE=`$COMMAND`
    curl_ret=$?
    #curl's exit status is 0 at authentication error

    expr "$PASSPHRASE" : '.*Error.*' > /dev/null
    jwt_ret=$?

    expr "$PASSPHRASE" : '.*<html>.*' > /dev/null
    jwt_ret2=$?

    if  [ $curl_ret -ne 0 ] || [ -z "$PASSPHRASE" ] || [ $jwt_ret -eq 0 ] || [ $jwt_ret2 -eq 0 ]; then
	#error
	if [ $jwt_ret2 -eq 0 ]; then
	    echo $ACCOUNT":Invalid Server"
        elif [ $curl_ret -eq 0 ]; then
            echo $ACCOUNT":Authentication Error"
	else
           continue;
	fi
	exit 1
    else
	echo $PASSPHRASE
	exit 0
    fi
done
