#!/bin/sh

CURL=curl

CMDNAME=$(basename $0)

if [ -n $JWT_SERVER_URL ]; then
  BASE_URL=$JWT_SERVER_URL
fi

if [ -n $LOGNAME ]; then
  ACCOUNT=$LOGNAME
fi

while getopts s:l:p: OPT
do
  case $OPT in
    "s" ) BASE_URL="$OPTARG" ;;
    "l" ) ACCOUNT="$OPTARG" ;;
      * ) echo "Usage: $CMDNAME [-s URL] [-l USER]" 1>&2
          exit 1 ;;
  esac
done

if [ -z "$BASE_URL" -o -z "$ACCOUNT" ]; then
 echo "Usage: $CMDNAME [-s URL] [-l USER]" 1>&2
 exit 1
fi

if [ -t 0 ]; then
  echo -n "Passphrase: "
  trap "stty echo" HUP INT QUIT TERM
  stty -echo
  read PASS
  stty echo

  echo
else
  read PASS
fi

URL=$BASE_URL/chpass

COMMAND="$CURL -m 10 -X POST -d user=$ACCOUNT -d pass=$PASS $URL"

PASSPHRASE=`$COMMAND 2>/dev/null`
curl_ret=$?
#curl's exit status is 0 at authentication error

expr "$JWT" : '.*Error.*' > /dev/null
jwt_ret=$?

if  [ $curl_ret -ne 0 ] || [ -z "$PASSPHRASE" ] || [ $jwt_ret -eq 0 ]; then
#error
  echo "Failed"
  exit 1
else
  echo $PASSPHRASE
  exit 0
fi
